from typing import Protocol

from classiflow.database.models import ConversationTurn


class IConversationRepository(Protocol):
    async def save_turn(self, user_email: str, question: str, answer: str) -> None: ...

    # Both methods return oldest-first (ascending created_at): recent_turns so the
    # history block prints in natural reading order, all_turns so MemoryService can
    # index the turn that just aged out of the raw window.
    async def recent_turns(self, user_email: str, limit: int) -> list[ConversationTurn]: ...

    async def all_turns(self, user_email: str) -> list[ConversationTurn]: ...

    async def turn_count(self, user_email: str) -> int: ...

    async def get_summary(self, user_email: str) -> str | None: ...

    async def save_summary(self, user_email: str, summary_text: str) -> None: ...

    async def clear(self, user_email: str) -> None: ...
