from typing import Protocol

from classiflow.shared.database.models import Job


class IJobRepository(Protocol):
    async def create(self, job: Job) -> None: ...
    async def find_by_job_id(self, job_id: str) -> Job | None: ...
    async def update_status(self, job_id: str, status: str) -> None: ...
    async def list_all(self) -> list[Job]: ...
